### ISSUE TITLE
problem about the knn tool in joern-tool

### ISSUE THREAD

**Issue by qingkunM** [fabsx00/joern#98]
I recently am working with "Finding Similar Functions with joern-tools'. When I use the knn, some problem appear. 
Command used:

joern-list-funcs -p flic_decode_frame_8BPP | awk -F "\t" '{print $2}' | joern-kn

and here is the error messages in terminal:

Traceback (most recent call last):
  File "/usr/local/bin/joern-knn", line 5, in <module>
    pkg_resources.run_script('joerntools==0.1', 'joern-knn')
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 528, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 1394, in run_script
    execfile(script_filename, namespace, namespace)
  File "/usr/local/lib/python2.7/dist-packages/joerntools-0.1-py2.7.egg/EGG-INFO/scripts/joern-knn", line 77, in <module>
    tool.run()
  File "/usr/local/lib/python2.7/dist-packages/joerntools-0.1-py2.7.egg/joerntools/shelltool/CmdLineTool.py", line 19, in run
    self._runImpl()
  File "/usr/local/lib/python2.7/dist-packages/joerntools-0.1-py2.7.egg/joerntools/shelltool/PipeTool.py", line 28, in _runImpl
    self._processStream()
  File "/usr/local/lib/python2.7/dist-packages/joerntools-0.1-py2.7.egg/joerntools/shelltool/PipeTool.py", line 36, in _processStream
    self.streamStart()
  File "/usr/local/lib/python2.7/dist-packages/joerntools-0.1-py2.7.egg/EGG-INFO/scripts/joern-knn", line 57, in streamStart
    self.knn.initialize()
  File "/usr/local/lib/python2.7/dist-packages/joerntools-0.1-py2.7.egg/joerntools/KNN.py", line 33, in initialize
    self.emb.x = Normalizer().fit_transform(self.emb.x)
AttributeError: 'NoneType' object has no attribute 'x'

Could it  possible for you to solve the problem? Thank you.

**Comment by qingkunM** [comment]
It turn out to be a sloppy mistake. When I followed the tutorial instructions, I don't pay attention to the failure of "joern-stream-apiembedder" instuction. Upon executing "joern-stream-apiembedder" before "joern-list-funcs -p flic_decode_frame_8BPP | awk -F "\t" '{print $2}' | joern-kn", everthing goes right.
